apiVersion: v1
kind: PersistentVolume
metadata:
  name: bp-backup-production-pv
spec:
  storageClassName: ""
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: bp-backup-production-pvc
  gcePersistentDisk:
    pdName: bp-production-backup-disk
    fsType: ext4
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bp-backup-production-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
