apiVersion: v1
kind: PersistentVolume
metadata:
  name: bp-backup-development-pv
spec:
#  storageClassName: ""
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: bp-backup-development-pvc
  gcePersistentDisk:
    pdName: bp-backup-development-disk
    fsType: ext4
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bp-backup-development-pvc
spec:
#  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
